### ISSUE TITLE
Gnome support

### ISSUE THREAD

**Issue by bdombro** [hrotkogabor/manjaro-btrfs#5]
This looks cool! I would consider using if it had a gnome mode that doesn’t install xfce stuff.

**Comment by hrotkogabor** [comment]
The basic flow is independent from xfce. Only the xfce folder contains the related scripts. 
Running the xfce scripts are optional as any other script like home encrypting, or lang_hu.sh . Those scripts are only optional additions.

**Comment by bdombro** [comment]
cool thanks!
